# Server
server.port=8080

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://sltnewsgeneration_user:news1234@jobify.fkdjpms.mongodb.net/sltnewsdb?retryWrites=true&w=majority

# File Upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Ollama
ollama.base-url=http://127.0.0.1:11434
ollama.model=llama3.2
ollama.vision-model=llava

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=monaachethiii@gmail.com
spring.mail.password=glbsntrodnrinmsj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File storage
file.upload-dir=./uploads